[package]
name = "smartshreds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adw = { version = "0.6", package = "libadwaita", features = ["v1_5"] }
gtk = { version = "0.8", package = "gtk4", features = ["v4_12"] }
walkdir = "2.5.0"
sha2 = "0.10.8"

[build-dependencies]
glib-build-tools = "0.19.0"
